name = "block"
main = "../scripts/block-login-flow/block-login-flow.js"
compatibility_date = "2025-09-15"
account_id = "c90a5323388a211e018b0c78e9b80335"
workers_dev = true
[observability.logs]
enabled = true